# Practical 01: Dataset Ingestion, Inspection & Descriptive Statistics with Pandas

**UNIT 1: Introduction to Big Data and Large Dataset Handling**

**Problem Statement:** Write a Python program using Pandas to load a structured dataset (CSV/JSON), display its first 5 rows, last 5 rows, dimensions (shape), column names, and data types with info(). Generate comprehensive summary statistics of all numeric and categorical attributes using describe(include='all').

In [1]:
import io
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None, "display.width", 200)

gen = np.random.default_rng(7)
n = 150
raw = pd.DataFrame({
    "Order ID": np.arange(1001, 1001 + n),
    "Customer Name": [f"Client_{i:03d}" for i in gen.integers(1, 45, n)],
    "City": gen.choice(["Delhi", "Jaipur", "Surat", "Indore", "Nagpur", "Pune"], n),
    "Product Category": gen.choice(["Electronics", "Clothing", "Groceries", "Toys", "Books"], n),
    "Quantity": gen.integers(1, 12, n),
    "Unit Price": np.round(gen.uniform(150, 4500, n), 2),
    "Discount %": gen.choice([0, 5, 10, 15, 25], n),
    "Order Date": pd.date_range("2025-03-01", periods=n, freq="D").strftime("%Y-%m-%d"),
})

csv_file = io.StringIO()
raw.to_csv(csv_file, index=False)
csv_file.seek(0)
json_file = io.StringIO(raw.to_json(orient="records"))

orders = pd.read_csv(csv_file)
print("Dataset loaded successfully!")

print(orders.head())

print(orders.tail())

print("Shape (rows, columns):", orders.shape)
print("Column names:", orders.columns.tolist())

orders.info()

print(orders.describe(include='all'))

df_json = pd.read_json(json_file)
print("JSON load – shape:", df_json.shape)
print(df_json.head())

Dataset loaded successfully!

   Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001     Client_042    Pune              Toys         9     2939.35           0  2025-03-01
1      1002     Client_028    Pune          Clothing         2      952.34          10  2025-03-02
2      1003     Client_031   Surat              Toys         5     3453.80          25  2025-03-03
3      1004     Client_040    Pune             Books         8     3445.95          15  2025-03-04
4      1005     Client_026  Indore              Toys         1     3287.63           0  2025-03-05

     Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
145      1146     Client_039   Surat         Groceries        10     2126.16           5  2025-07-24
146      1147     Client_005   Delhi          Clothing         1     3413.75           5  2025-07-25
147      1148     Client_030  Indore              Toys         9     3226.82          10  2025-07-26
148      1149     Client_024  Indore          Clothing         7     2557.55           0  2025-07-27
149      1150     Client_006    Pune              Toys         5     3660.65          10  2025-07-28

Shape (rows, columns): (150, 8)
Column names: ['Order ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Price', 'Discount %', 'Order Date']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          150 non-null    int64
 1   Customer Name     150 non-null    object
 2   City              150 non-null    object
 3   Product Category  150 non-null    object
 4   Quantity          150 non-null    int64
 5   Unit Price        150 non-null    float64
 6   Discount %        150 non-null    int64
 7   Order Date        150 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 9.5+ KB

           Order ID  Customer Name  City  Product Category    Quantity   Unit Price  Discount %  Order Date
 count   150.000000            150   150               150  150.000000   150.000000  150.000000         150
unique          NaN             41     6                 5         NaN          NaN         NaN         150
   top          NaN     Client_020  Pune              Toys         NaN          NaN         NaN  2025-03-01
  freq          NaN              6    37                35         NaN          NaN         NaN           1
  mean  1075.500000            NaN   NaN               NaN    6.140000  2379.486133   10.866667         NaN
   std    43.445368            NaN   NaN               NaN    3.108831  1269.528808    8.166610         NaN
   min  1001.000000            NaN   NaN               NaN    1.000000   217.130000    0.000000         NaN
   25%  1038.250000            NaN   NaN               NaN    3.000000  1142.022500    5.000000         NaN
   50%  1075.500000            NaN   NaN               NaN    6.000000  2434.265000   10.000000         NaN
   75%  1112.750000            NaN   NaN               NaN    9.000000  3451.837500   15.000000         NaN
   max  1150.000000            NaN   NaN               NaN   11.000000  4479.820000   25.000000         NaN

JSON load – shape: (150, 8)

   Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001     Client_042    Pune              Toys         9     2939.35           0  2025-03-01
1      1002     Client_028    Pune          Clothing         2      952.34          10  2025-03-02
2      1003     Client_031   Surat              Toys         5     3453.80          25  2025-03-03
3      1004     Client_040    Pune             Books         8     3445.95          15  2025-03-04
4      1005     Client_026  Indore              Toys         1     3287.63           0  2025-03-05